Repository felipesbcabral/financify-frontend, pull requests merged in 2023-06, with the labels that each got.

#27 [Feature] #26 Realiza integração com API backend
  package-lock.json
  package.json
  src/App.jsx
  src/Styles/Erro.css
  src/Styles/Home.css
  src/Styles/LoginPage.css
  src/Styles/Navbar.scss
  src/Styles/New.module.css
  src/Styles/NewValues.css
  src/Styles/SpashScreen.css
  src/components/Navbar.jsx
  src/contexts/AuthProvider.jsx
  src/index.css
  src/pages/EditChargePage.jsx
  src/pages/Erro.jsx
  src/pages/Home.jsx
  src/pages/LoginPage.jsx
  src/pages/NewValues.jsx
  src/pages/RegisterPage.jsx
  src/pages/SpashScreen.jsx
Labels: enhancement, Feature

#39 [Feature] Adiciona configuraçoes default para a aplicação #33
  src/contexts/AuthProvider.jsx
  src/pages/EditChargePage.jsx
  src/pages/Home.jsx
  src/pages/NewValues.jsx
  src/pages/RegisterPage.jsx
Labels: enhancement, Feature

#44 [Feature] Realiza implementação do esqueceu senha #43
  src/App.jsx
  src/pages/ForgotPassword.jsx
  src/pages/RegisterPage.jsx
  src/pages/ResetPassword.jsx
Labels: Feature

#46 [Feature] Realiza implementação do mostrar saldo e do depositar #45
  package-lock.json
  package.json
  src/App.jsx
  src/Styles/DepositarSaldo.css
  src/Styles/Home.css
  src/components/Navbar.jsx
  src/pages/DepositarSaldo.jsx
  src/pages/EditChargePage.jsx
  src/pages/Home.jsx
  src/pages/NewValues.jsx
Labels: Feature

#50 [Improvement] Padronizacao de cores da aplicacao #49
  src/Styles/DepositarSaldo.css
  src/Styles/EditCharges.css
  src/Styles/NewValues.css
  src/Styles/config.css
  src/Styles/dados.css
  src/Styles/privacidade.css
  src/Styles/support.css
  src/assets/default-avatar.jpg
  src/pages/DepositarSaldo.jsx
  src/pages/EditChargePage.jsx
  src/pages/NewValues.jsx
  src/pages/config.jsx
  src/pages/dados.jsx
  src/pages/privacidade.jsx
  src/pages/support.jsx
Labels: enhancement

#55 padronização de cor das paginas de login e inicial #53
  src/Styles/LoginPage.css
  src/Styles/initialPage.css
Labels: enhancement

#56 Bugfix/realiza o fix do status da cobranca/#54
  src/pages/EditChargePage.jsx
  src/pages/NewValues.jsx
Labels: bug

#69 [Improvement] Padroniza cores dos botões #68
  src/Styles/CadastroUsuarios.css
  src/Styles/EsqueciSenha.css
  src/pages/ForgotPassword.jsx
Labels: enhancement

#77 [Feature] Refatora projeto para tailwind #76
  index.html
  package-lock.json
  package.json
  postcss.config.cjs
  src/App.jsx
  src/Styles/CadastroUsuarios.css
  src/Styles/DepositarSaldo.css
  src/Styles/EditCharges.css
  src/Styles/Erro.css
  src/Styles/EsqueciSenha.css
  src/Styles/Home.css
  src/Styles/LoginPage.css
  src/Styles/Navbar.scss
  src/Styles/NewValues.css
  src/Styles/config.css
  src/Styles/dados.css
  src/Styles/initialPage.css
  src/Styles/privacidade.css
  src/Styles/support.css
  src/assets/financify-logo.jpg
  src/components/Footer.jsx
  src/components/Layout.jsx
  src/components/Navbar.jsx
  src/contexts/AuthProvider.jsx
  src/index.css
  src/pages/DepositarSaldo.jsx
  src/pages/EditChargePage.jsx
  src/pages/Erro.jsx
  src/pages/ForgotPassword.jsx
  src/pages/Home.jsx
  src/pages/LoginPage.jsx
  src/pages/NewValues.jsx
  src/pages/RegisterPage.jsx
  src/pages/ResetPassword.jsx
  src/pages/config.jsx
  src/pages/dados.jsx
  src/pages/initialPage.jsx
  src/pages/privacidade.jsx
  src/pages/support.jsx
  tailwind.config.js
Labels: bug, enhancement, Feature

#79 [Feature] Adiciona validação na criação e edição de cobrança #78
  src/pages/EditChargePage.jsx
  src/pages/NewValues.jsx
Labels: enhancement
